# Generated by Django 3.2.12 on 2022-12-02 06:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=64)),
                ('is_center', models.BooleanField(default=False)),
                ('current_global_round', models.IntegerField(blank=True, null=True)),
                ('current_model_path', models.CharField(blank=True, max_length=512, null=True)),
                ('train_acc', models.FloatField(blank=True, null=True)),
                ('train_loss', models.FloatField(blank=True, null=True)),
                ('api_url', models.CharField(max_length=256)),
                ('is_active', models.BooleanField(default=True)),
                ('epochs', models.IntegerField(blank=True, null=True)),
                ('use_gpu', models.BooleanField(default=False)),
                ('num_channels', models.IntegerField(blank=True, null=True)),
                ('num_classes', models.IntegerField(blank=True, null=True)),
                ('batch_size', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'device',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('event_type', models.CharField(max_length=128)),
                ('model_path', models.CharField(blank=True, max_length=512, null=True)),
                ('global_round', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=128, null=True)),
                ('train_acc', models.FloatField(blank=True, null=True)),
                ('train_loss', models.FloatField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='device.device')),
            ],
            options={
                'db_table': 'event',
            },
        ),
    ]
