# Generated by Django 3.2.12 on 2022-12-03 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='train_acc_list',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='train_loss_list',
            field=models.TextField(blank=True, null=True),
        ),
    ]
