# Generated by Django 3.2.12 on 2022-11-26 13:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=64)),
                ('current_model_path', models.CharField(blank=True, max_length=512, null=True)),
            ],
            options={
                'db_table': 'client',
            },
        ),
    ]
