# Generated by Django 3.2.12 on 2022-12-03 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='api_url',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
