# Generated by Django 3.2.12 on 2022-11-23 15:04

import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CenterConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('value', models.TextField(max_length=128)),
                ('data_type', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='CenterEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('global_round', models.IntegerField()),
                ('event_type', models.CharField(choices=[('center_received_params', 'Center Received Params'), ('center_sent_params', 'Center Sent Params')], max_length=128)),
                ('params', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='client.client')),
            ],
        ),
    ]
